config/routes.rb
Rails.application.routes.draw do
  get 'contact/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home" 
  # OR 
  # get "/", to: "pages#home", as: "root"
  # get "/", to: "pages#home"
  post "/data/:computer/:type/:id", to: "pages#data"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/book.rb
class Book < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # to eleminate the 422 error, which verifies the authenticity tokken 
  # to be sent from the browser
  # this is only for test purpose, don't add this to production
  skip_before_action :verify_authenticity_token
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def page
     @user = nil
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :before_run
  after_action :after_run

  def home
    @names = ["ana", "cat", "angeline"]
    @user = nil
    # puts "hey this is home page"
    # render keyword send response back to the browser
    # render "page/root"
    
  end

  def data
    # params contains the controller, method name and the data that is sent in the request
    # query params: capture the data coming through the url following
    # body params
    # dynamic url
    # puts params[:profile][:hobby]
    puts "2"
    puts params
   
    # render plain: "post request is working"
    # redirect navigates to another route 
    redirect_to "/"
  end

def before_run
  puts "1.run before the data or home method"
end

def after_run
  puts "3.runs after the data and home method"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/page.html.erb
<h1>Contact!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControllerLesson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render "shared/top_nav", user: @user %>
  
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>hey this is home page</h1>

<% @names.each do |name| %>
  <li><%= name %></li>
<% end %>

app/views/shared/_top_nav.html.erb
<h1>hey <%= user %> </h1>
<%= "hey #{user}" if user.present? %>

<nav>
  <ul>
    <li><%= link_to("Home", root_path) %></li>
    <li><%= link_to("Contact", contact_page_path) %></li>
  </ul>

</nav>